# Generated by Django 2.2.4 on 2019-08-14 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('investment_name', models.CharField(max_length=120)),
                ('capital_requirement', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MaxValueValidator(100000000000), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MaxValueValidator(100000000000), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FundInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MaxValueValidator(100000000000), django.core.validators.MinValueValidator(1)])),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_investments', to='capital_calls.Call')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_investments', to='capital_calls.Commitment')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_investments', to='capital_calls.Fund')),
            ],
        ),
        migrations.AddField(
            model_name='commitment',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='capital_calls.Fund'),
        ),
    ]
